name              "distelli"
maintainer        "Brian Maher"
maintainer_email  "bmaher@distelli.com"
license           "All rights reserved"
description       "Installs Distelli Agent"
version           "1.1.0"
recipe            "distelli", "Installs Distelli Agent"
